---
title: "Informe"
format:
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
---

```{r}
library(odbc)
library(DBI)
library(dplyr)
library(ggplot2)
library(gt)
```

```{r}
keys <- readLines("keys.txt", warn = FALSE)
username <- gsub("username:", "", keys[1])
password <- gsub("password:", "", keys[2])
```

```{r}

con <- dbConnect(odbc(),
                 Driver = "SQL Server",
                 Server = "157.92.26.17,1443",
                 Database = "AdventureWorksDW2019",
                 UID = username,
                 PWD = password)
          
```

## Ejemplo query 10

```{r}
query10 <- "WITH producto_venta_reseller AS (SELECT rsales.ProductKey, rsales.OrderQuantity, rsales.SalesOrderNumber, dr.ResellerName, rsales.PromotionKey
FROM dbo.FactResellerSales rsales
LEFT JOIN dbo.DimReseller dr ON rsales.ResellerKey = dr.ResellerKey
WHERE YEAR(rsales.OrderDate) IN (2010, 2011, 2012, 2013)),
sod_reseller AS(
    SELECT DISTINCT SalesOrderNumber, ResellerName
    FROM producto_venta_reseller
),
total_vtas_reseller AS(
    SELECT ResellerName, COUNT(*) as total_ventas
    FROM producto_venta_reseller
    GROUP BY ResellerName
),
total_items_reseller AS (
    SELECT ResellerName, SUM(OrderQuantity) as total_productos
    FROM producto_venta_reseller
    GROUP BY ResellerName
)
SELECT tvr.ResellerName, total_ventas, tir.total_productos
FROM total_vtas_reseller tvr
LEFT JOIN total_items_reseller tir ON tvr.ResellerName = tir.ResellerName"
```

```{r}
q10 <- dbGetQuery(con, query10)
print(q10)
```

## Query 5

```{r}
query5 <- "WITH helper1 AS (SELECT DISTINCT isales.SalesOrderNumber, categ.SpanishProductCategoryName,
CASE WHEN isales.PromotionKey = '1' THEN 'sin_promocion'
ELSE 'con_promocion'
END AS 'con_sin_promo'
FROM dbo.FactInternetSales isales
LEFT JOIN dbo.DimProduct prod ON isales.ProductKey = prod.ProductKey
LEFT JOIN dbo.DimProductSubcategory sub ON prod.ProductSubcategoryKey = sub.ProductSubcategoryKey
LEFT JOIN dbo.DimProductCategory categ ON sub.ProductCategoryKey = categ.ProductCategoryKey
WHERE YEAR(isales.OrderDate) IN (2010, 2011, 2012, 2013)),
helper2 AS (
SELECT SpanishProductCategoryName, con_sin_promo, COUNT(*) as total
FROM helper1
GROUP BY SpanishProductCategoryName, con_sin_promo),
helper3 AS(
SELECT
  SpanishProductCategoryName,
  SUM(CASE WHEN con_sin_promo = 'con_promocion' THEN total END) AS con_promocion,
  SUM(CASE WHEN con_sin_promo = 'sin_promocion' THEN total END) AS sin_promocion,
  SUM(total) AS total_categoria
FROM helper2
GROUP BY SpanishProductCategoryName)
SELECT SpanishProductCategoryName, con_promocion, sin_promocion, (con_promocion *100/total_categoria) as porc_con_promocion, (sin_promocion *100/total_categoria) as porc_sin_promocion
FROM helper3"

q5 <- dbGetQuery(con, query5)
q5 %>% 
  gt() %>% 
  tab_header(title = md('**Porcentaje de ventas totales que se hacen c/sin promoción**'),
                     subtitle = 'Por categoría. Período 2010-2013' ) %>%
  opt_align_table_header('left')
```

## Query 6

```{r}
query6 <- "SELECT isales.PromotionKey, COUNT(*) as total_uso_id_promo
FROM dbo.FactInternetSales isales
LEFT JOIN dbo.DimProduct prod ON isales.ProductKey = prod.ProductKey
WHERE isales.PromotionKey != '1'
AND YEAR(isales.OrderDate) IN (2010, 2011, 2012, 2013)
GROUP BY isales.PromotionKey
ORDER BY total_uso_id_promo DESC"

q6 <- dbGetQuery(con, query6)
q6 %>% 
  gt() %>% 
  tab_header(title = md('**Promociones más aplicadas**'),
                     subtitle = 'Período 2010-2013' ) %>%
  opt_align_table_header('left')
```

## Query 7

```{r}
query7 <- "WITH orderid_reseller AS (SELECT DISTINCT rsales.SalesOrderNumber, dr.ResellerName
FROM dbo.FactResellerSales rsales
LEFT JOIN dbo.DimReseller dr ON rsales.ResellerKey = dr.ResellerKey
WHERE YEAR(rsales.OrderDate) IN (2010, 2011, 2012, 2013))
SELECT TOP 5 ResellerName, COUNT(*) as total_ventas
FROM orderid_reseller
GROUP BY ResellerName
ORDER BY total_ventas DESC"
q7 <- dbGetQuery(con, query7)
q7 %>% 
  gt() %>% 
  tab_header(title = md('**Análisis exploratorio**'),
                     subtitle = 'Distribución de las variables numéricas' ) %>%
  opt_align_table_header('left')
```

## Query 8

```{r}
query8 <- "WITH orden_reseller_anio AS (
    SELECT DISTINCT rsales.SalesOrderNumber, dr.ResellerName, YEAR(rsales.OrderDate) AS anio
    FROM dbo.FactResellerSales rsales
    LEFT JOIN dbo.DimReseller dr ON rsales.ResellerKey = dr.ResellerKey
    WHERE YEAR(rsales.OrderDate) IN (2010, 2011, 2012, 2013)
),
top_resellers AS (
    SELECT TOP 5 ResellerName, COUNT(*) AS total_ventas
    FROM dbo.FactResellerSales rsales
    LEFT JOIN dbo.DimReseller dr ON rsales.ResellerKey = dr.ResellerKey
    WHERE YEAR(rsales.OrderDate) IN (2010, 2011, 2012, 2013)
    GROUP BY ResellerName
    ORDER BY COUNT(*) DESC
)
SELECT ora.ResellerName, anio, COUNT(*) AS total_ventas_reseller_anio
FROM orden_reseller_anio ora
JOIN top_resellers ON ora.ResellerName = top_resellers.ResellerName
GROUP BY ora.ResellerName, anio"
q8 <- dbGetQuery(con, query8)
q8 %>% 
  gt() %>% 
  tab_header(title = md('**Recorrido de mejores resellers**'),
                     subtitle = 'Año a año' ) %>%
  opt_align_table_header('left')
```

### Línea de tiempo

## Query 9

```{r}
query9 <- "WITH producto_venta_reseller AS (SELECT rsales.ProductKey, rsales.SalesOrderNumber, dr.ResellerName, rsales.PromotionKey
FROM dbo.FactResellerSales rsales
LEFT JOIN dbo.DimReseller dr ON rsales.ResellerKey = dr.ResellerKey
WHERE YEAR(rsales.OrderDate) IN (2010, 2011, 2012, 2013)),
sod_reseller AS(
    SELECT DISTINCT SalesOrderNumber, ResellerName
    FROM producto_venta_reseller
),
total_vtas_reseller AS(
    SELECT ResellerName, COUNT(*) as total_ventas
    FROM producto_venta_reseller
    GROUP BY ResellerName
),
ventas_con_promo AS (
    SELECT DISTINCT ResellerName, SalesOrderNumber
    FROM producto_venta_reseller
    WHERE PromotionKey != '1'
),
total_vtas_reseller_promo AS (
    SELECT ResellerName, COUNT(*) as total_ventas_promo
    FROM ventas_con_promo
    GROUP BY ResellerName
), totales AS (
SELECT tvr.ResellerName, tvr.total_ventas, ISNULL(tvrp.total_ventas_promo, 0) as total_ventas_promo
FROM total_vtas_reseller tvr
LEFT JOIN total_vtas_reseller_promo tvrp ON tvr.ResellerName = tvrp.ResellerName)
SELECT ResellerName, total_ventas, total_ventas_promo, (total_ventas_promo*100/total_ventas) as porc_vtas_con_promo
FROM totales
ORDER BY porc_vtas_con_promo DESC"
q9 <- dbGetQuery(con, query9)
q9 %>% 
  gt() %>% 
  tab_header(title = md('**Vendedores que aplicaron la mayor cantidad de promociones**'),
                     subtitle = 'En relación a sus ventas 2010-2013' ) %>%
  opt_align_table_header('left')
```

## Query 10

```{r}
query10 <- "WITH producto_venta_reseller AS (SELECT rsales.ProductKey, rsales.OrderQuantity, rsales.SalesOrderNumber, dr.ResellerName, rsales.PromotionKey
FROM dbo.FactResellerSales rsales
LEFT JOIN dbo.DimReseller dr ON rsales.ResellerKey = dr.ResellerKey
WHERE YEAR(rsales.OrderDate) IN (2010, 2011, 2012, 2013)),
sod_reseller AS(
    SELECT DISTINCT SalesOrderNumber, ResellerName
    FROM producto_venta_reseller
),
total_vtas_reseller AS(
    SELECT ResellerName, COUNT(*) as total_ventas
    FROM producto_venta_reseller
    GROUP BY ResellerName
),
total_items_reseller AS (
    SELECT ResellerName, SUM(OrderQuantity) as total_productos
    FROM producto_venta_reseller
    GROUP BY ResellerName
)
SELECT tvr.ResellerName, total_ventas, tir.total_productos
FROM total_vtas_reseller tvr
LEFT JOIN total_items_reseller tir ON tvr.ResellerName = tir.ResellerName"
q10 <- dbGetQuery(con, query10)

```

### Tabla

```{r}
q10 %>% 
  gt() %>% 
  tab_header(title = md('**Vendedores proactivos**'),
                     subtitle = 'Ventas realizadas vs Total de ítems vendidos' ) %>%
  opt_align_table_header('left')
```

### Scatterplot

```{r}

```
